matrix:
  include:
    - language: node_js
      node_js:
        - v6
      before_script:
        - cd frontend/
      script:
        - npm install && npm run
      cache:
        - yarn
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: python
      python: 3.5.2
      before_script:
        - cd backend/
        - virtualenv -p python3 env
        - source env/bin/activate
        - pip install -r requirements.txt
      script:
        - python manage.py runserver

notifications:
  email:
    - keyxiz@gmail.com
