matrix:
  include:
    - language: node_js
      node_js:
        - v6
      before_script:
        - cd frontend/
      script:
        - npm install && npm run
      cache:
        - yarn
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: python
      python: 3.5.2
      before_script:
        - cd backend/
        - python3 manage.py runserver &
      install:
        - pip3 install -r ./backend/requirements.txt
      script:
        - sh ./init.sh
        - python3 runtest.py

notifications:
  email:
    - keyxiz@gmail.com
